from Linked_List import Node, linkedList  

ll = linkedList()

node_a = Node('Seven Nation Army', 'The White Stripes', 'Elephant')
node_b = Node('Thunderstruck', 'AC/DC', 'The Razors Edge')
node_c = Node('Lose Yourself', 'Eminem', 'Curtain Call')
node_d = Node('Eye of the Tiger', 'Survivor', 'Eye of the Tiger')
node_e = Node('We Will Rock You', 'Queen', 'News of the World')
node_f = Node('Remember the Name', 'Fort Minor', 'The Rising Tied')
node_g = Node('Believer', 'Imagine Dragons', 'Evolve')
node_h = Node('Till I Collapse', 'Eminem', 'The Eminem Show')
node_i = Node('Power', 'Kanye West', 'My Beautiful Dark Twisted Fantasy')
node_j = Node('Stronger', 'Kanye West', 'Graduation')
node_k = Node('All of the Lights', 'Kanye West', 'My Beautiful Dark Twisted Fantasy')
node_l = Node('The Final Countdown', 'Europe', 'The Final Countdown')
node_m = Node('Can’t Hold Us', 'Macklemore & Ryan Lewis', 'The Heist')
node_n = Node('X Gon Give It To Ya', 'DMX', 'The Definition of X')
node_o = Node('Jump Around', 'House of Pain', 'House of Pain')
node_p = Node('HUMBLE', 'Kendrick Lamar', 'DAMN')
node_q = Node('Sicko Mode', 'Travis Scott', 'Astroworld')
node_r = Node('Industry Baby', 'Lil Nas X', 'Montero')
node_s = Node('DNA', 'Kendrick Lamar', 'DAMN')
node_t = Node('All the Way Up', 'Fat Joe & Remy Ma', 'Plata O Plomo')
node_u = Node('Welcome to the Jungle', 'Guns N Roses', 'Appetite for Destruction')
node_v = Node('Enter Sandman', 'Metallica', 'Metallica')
node_w = Node('Centuries', 'Fall Out Boy', 'American Beauty/American Psycho')
node_x = Node('My Songs Know What You Did in the Dark', 'Fall Out Boy', 'Save Rock and Roll')
node_y = Node('Warriors', 'Imagine Dragons', 'Smoke + Mirrors')
node_z = Node('Radioactive', 'Imagine Dragons', 'Night Visions')
node_aa = Node('Titanium', 'David Guetta', 'Nothing but the Beat')
node_ab = Node('Animals', 'Martin Garrix', 'Gold Skies')
node_ac = Node('Levels', 'Avicii', 'True')
node_ad = Node('Turn Down for What', 'DJ Snake & Lil Jon', 'Encore')
node_ae = Node('Don’t Stop Me Now', 'Queen', 'Jazz')
node_af = Node('We Are the Champions', 'Queen', 'News of the World')
node_ag = Node('Born to Be Wild', 'Steppenwolf', 'Steppenwolf')
node_ah = Node('Pump It', 'Black Eyed Peas', 'Monkey Business')
node_ai = Node('Party Up', 'DMX', '...And Then There Was X')
node_aj = Node('Can’t Be Touched', 'Roy Jones Jr', 'Body Head Bangerz')
node_ak = Node('Hall of Fame', 'The Script', '3')
node_al = Node('Unstoppable', 'Sia', 'This Is Acting')
node_am = Node('Legends Never Die', 'Against The Current', 'League of Legends')
node_an = Node('Enemy', 'Imagine Dragons', 'Mercury Act 1')
node_ao = Node('Run This Town', 'Jay-Z', 'The Blueprint 3')
node_ap = Node('Lose Control', 'Missy Elliott', 'The Cookbook')
node_aq = Node('Dangerous', 'David Guetta', 'Listen')
node_ar = Node('Firestarter', 'The Prodigy', 'The Fat of the Land')
node_as = Node('Ready For It', 'Taylor Swift', 'Reputation')
node_at = Node('All I Do Is Win', 'DJ Khaled', 'Victory')
node_au = Node('Dreams and Nightmares', 'Meek Mill', 'Dreams and Nightmares')
node_av = Node('Power Glove', 'Knife Party', 'Abandon Ship')
node_aw = Node('Animals', 'Nickelback', 'All the Right Reasons')
node_ax = Node('Remember the Name', 'Fort Minor', 'The Rising Tied')

ll.insert_at_beginning(node_a)
ll.insert_at_beginning(node_b)
ll.insert_at_beginning(node_c)
ll.insert_at_beginning(node_d)
ll.insert_at_beginning(node_e)
ll.insert_at_beginning(node_f)
ll.insert_at_beginning(node_g)
ll.insert_at_beginning(node_h)
ll.insert_at_beginning(node_i)
ll.insert_at_beginning(node_j)
ll.insert_at_beginning(node_k)
ll.insert_at_beginning(node_l)
ll.insert_at_beginning(node_m)
ll.insert_at_beginning(node_n)
ll.insert_at_beginning(node_o)
ll.insert_at_beginning(node_p)
ll.insert_at_beginning(node_q)
ll.insert_at_beginning(node_r)
ll.insert_at_beginning(node_s)
ll.insert_at_beginning(node_t)
ll.insert_at_beginning(node_u)
ll.insert_at_beginning(node_v)
ll.insert_at_beginning(node_w)
ll.insert_at_beginning(node_x)
ll.insert_at_beginning(node_y)
ll.insert_at_beginning(node_z)
ll.insert_at_beginning(node_aa)
ll.insert_at_beginning(node_ab)
ll.insert_at_beginning(node_ac)
ll.insert_at_beginning(node_ad)
ll.insert_at_beginning(node_ae)
ll.insert_at_beginning(node_af)
ll.insert_at_beginning(node_ag)
ll.insert_at_beginning(node_ah)
ll.insert_at_beginning(node_ai)
ll.insert_at_beginning(node_aj)
ll.insert_at_beginning(node_ak)
ll.insert_at_beginning(node_al)
ll.insert_at_beginning(node_am)
ll.insert_at_beginning(node_an)
ll.insert_at_beginning(node_ao)
ll.insert_at_beginning(node_ap)
ll.insert_at_beginning(node_aq)
ll.insert_at_beginning(node_ar)
ll.insert_at_beginning(node_as)
ll.insert_at_beginning(node_at)
ll.insert_at_beginning(node_au)
ll.insert_at_beginning(node_av)
ll.insert_at_beginning(node_aw)
ll.insert_at_beginning(node_ax)
print(ll)
